spring:
  application:
    name: spring-cloud-eureka-client-dk
server:
  port: 9111
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true